import './style.css'
import { supabase } from './supabase.js'

let profiles = []
let matches = []
let likedProfileIds = new Set()
let unreadMessageCounts = new Map()

let activeProfile = 0
let savedIds = new Set()
let profileCreated = Boolean(localStorage.getItem('connects-profile'))
let profileVisible = JSON.parse(localStorage.getItem('connects-profile') || '{}').is_visible !== false
let blockedPeople = JSON.parse(localStorage.getItem('connects-blocked') || '[]')

document.querySelector('#app').innerHTML = `
  <header class="topbar"><a class="brand" href="#discover" aria-label="Charlotte Connect home"><span class="brand-mark">✦</span> Charlotte Connect</a><nav class="nav-links" aria-label="Main navigation"><a class="active" id="nav-discover" href="#discover">Discover</a><a id="nav-connections" href="#connections">Connections <span class="nav-count" id="connection-nav-count">0</span></a><a id="nav-profile" href="#profile">Profile</a></nav></header>
  <main>
    <section class="browse-shell discovery-view" aria-label="Discover profiles">
      <aside class="filters"><div class="filter-heading"><span>How are you connecting?</span></div><label class="filter-label" for="interest">I'm looking for</label><select id="interest"><option>Relationship</option><option>Friend</option></select><div class="filter-note"><span>☼</span><p>We only show verified<br />Charlotte student emails.</p></div></aside>
      <div class="profile-stage"><div class="stage-top"><span id="profile-count">1 of 3 profiles</span></div><article class="profile-card" id="profile-card" tabindex="0" role="button" aria-label="Swipe profile left to pass or right to like"></article><p class="action-hint">Swipe left to pass · swipe right to like</p></div>
    </section>
    <section class="page-view connections-page" id="connections-page" aria-labelledby="connections-title"><div class="page-heading"><div><div class="eyebrow">Your people</div><h2 id="connections-title">Connections</h2><p>Mutual likes, ready for a real conversation.</p></div><span class="page-count" id="connection-count">0 matches</span></div><div class="connection-grid"></div></section>
    <section class="page-view profile-page" id="profile-page" aria-labelledby="profile-page-title"><div class="page-heading"><div><div class="eyebrow">Your details</div><h2 id="profile-page-title">My profile</h2><p>Keep the details that help the right people find you.</p></div><span class="profile-status">● Live profile</span></div><form class="profile-edit-form" id="profile-edit-form"><div class="profile-edit-grid"><div class="edit-full photo-field"><label for="edit-photo">Profile photo</label><input id="edit-photo" type="file" accept="image/png,image/jpeg,image/webp" /><img id="edit-photo-preview" class="photo-preview" alt="Profile preview" /></div><div><label for="edit-name">First name</label><input id="edit-name" type="text" required /></div><div><label for="edit-age">Age</label><input id="edit-age" type="number" min="18" max="99" required /></div><div><label for="edit-major">Major</label><input id="edit-major" type="text" required /></div><div><label for="edit-year">Class year</label><select id="edit-year"><option>Freshman</option><option>Sophomore</option><option>Junior</option><option>Senior</option><option>Graduate</option></select></div><div><label for="edit-intent">I'm looking for</label><select id="edit-intent"><option>Relationship</option><option>Friend</option></select></div><div class="edit-full"><label for="edit-bio">About you</label><textarea id="edit-bio" rows="5" maxlength="180"></textarea></div></div><div class="profile-edit-footer"><span id="profile-email"></span><button class="primary-button" type="submit">Save changes <span>→</span></button></div></form></section>
  </main>
  <div class="toast" id="toast" role="status"></div>
  <div class="modal-backdrop" id="profile-modal" aria-hidden="true"><div class="auth-modal" role="dialog" aria-modal="true" aria-labelledby="profile-title"><button class="close-modal" id="close-profile" aria-label="Close">×</button><span class="modal-mark">✦</span><h2 id="profile-title">Welcome to Connects.</h2><p>Sign in or create your Niner account to continue.</p><form id="profile-form"><label for="email">Your student email</label><input id="email" type="email" placeholder="you@charlotte.edu" autocomplete="email" required /><label for="password">Password</label><input id="password" type="password" minlength="8" placeholder="At least 8 characters" autocomplete="new-password" required /><div class="auth-mode"><button class="auth-mode-button active" id="mode-signup" type="button">Create account</button><button class="auth-mode-button" id="mode-signin" type="button">Sign in</button></div><button class="primary-button" id="auth-submit" type="submit">Create account <span>→</span></button><p class="confirmation-note" id="confirmation-note" hidden>Check your email for a confirmation link. Once confirmed, return here to finish your profile.</p><div class="profile-fields" id="profile-fields" aria-disabled="true"><label for="profile-photo">Profile photo</label><input id="profile-photo" type="file" accept="image/png,image/jpeg,image/webp" /><img id="profile-photo-preview" class="photo-preview" alt="Profile preview" /><div class="form-row"><div><label for="profile-name">First name</label><input id="profile-name" type="text" placeholder="Maya" required disabled /></div><div><label for="profile-age">Age</label><input id="profile-age" type="number" min="18" max="99" placeholder="21" required disabled /></div></div><label for="profile-major">Major</label><input id="profile-major" type="text" placeholder="Architecture" required disabled /><label for="profile-year">Class year</label><select id="profile-year" disabled><option>Freshman</option><option>Sophomore</option><option>Junior</option><option>Senior</option><option>Graduate</option></select><label for="profile-intent">I'm looking for</label><select id="profile-intent" disabled><option>Relationship</option><option>Friend</option></select><label for="profile-bio">A little about you <span class="optional">Optional</span></label><textarea id="profile-bio" rows="3" maxlength="180" placeholder="A good coffee spot, a favorite class, or something you want to try..." disabled></textarea><button class="primary-button" id="create-profile" type="submit" disabled>Create my profile <span>→</span></button></div><small>Only @charlotte.edu and @uncc.edu emails are accepted.</small></form></div></div>
`

document.body.classList.toggle('profile-required', !profileCreated)
document.querySelector('#profile-page .page-heading').insertAdjacentHTML('afterend', '<section class="blocked-panel" aria-labelledby="blocked-title"><div><div class="eyebrow">Your boundaries</div><h3 id="blocked-title">Blocked people</h3><p>Block someone by name or email. They will not appear in your discovery or connections.</p></div><form id="block-form"><label for="block-person">Name or email</label><div class="block-input-row"><input id="block-person" type="text" placeholder="name or email" required /><button type="submit">Block <span>×</span></button></div></form><div id="blocked-list"></div></section>')
document.querySelector('#app').insertAdjacentHTML('beforeend', '<div class="message-modal" id="message-modal" aria-hidden="true"><div class="message-panel" role="dialog" aria-modal="true" aria-labelledby="message-title"><button class="message-close" id="message-close" type="button" aria-label="Close messages">×</button><div class="eyebrow">Mutual connection</div><h2 id="message-title">Messages</h2><div class="message-list" id="message-list"></div><form id="message-form"><input id="message-input" type="text" maxlength="500" placeholder="Write a message..." autocomplete="off" required /><button type="submit">Send <span>→</span></button></form></div></div>')
document.querySelector('.filters').innerHTML = '<div class="filter-heading"><span>Profile filters</span><button id="reset-discovery-filters" type="button">Reset</button></div><label class="filter-label" for="filter-age">Age</label><select id="filter-age"><option value="all">Any age</option><option value="18-21">18–21</option><option value="22-25">22–25</option><option value="26+">26+</option></select><label class="filter-label" for="filter-gender">Gender</label><select id="filter-gender"><option value="all">Any gender</option><option>Woman</option><option>Man</option><option>Non-binary</option><option>Genderqueer</option><option>Other</option></select><label class="filter-label" for="filter-sexuality">Sexuality</label><select id="filter-sexuality"><option value="all">Any sexuality</option><option>Straight</option><option>Gay</option><option>Lesbian</option><option>Bisexual</option><option>Pansexual</option><option>Asexual</option><option>Queer</option><option>Other</option></select><label class="filter-label" for="filter-height">Height</label><select id="filter-height"><option value="all">Any height</option><option value="under-5-6">Under 5 ft 6 in</option><option value="5-6-6">5 ft 6 in – 6 ft</option><option value="over-6">Over 6 ft</option></select><label class="filter-label" for="filter-ethnicity">Ethnicity</label><select id="filter-ethnicity"><option value="all">Any ethnicity</option><option>Asian</option><option>Black</option><option>Latina</option><option>White</option><option>Multiracial</option></select><label class="filter-label" for="filter-hair">Hair color</label><select id="filter-hair"><option value="all">Any hair color</option><option>Black</option><option>Brown</option><option>Blonde</option><option>Red</option></select><label class="filter-label" for="filter-drinking">Drinking</label><select id="filter-drinking"><option value="all">Any preference</option><option>Never</option><option>Sometimes</option><option>Often</option></select><label class="filter-label" for="filter-smoking">Smoking</label><select id="filter-smoking"><option value="all">Any preference</option><option>Never</option><option>Sometimes</option><option>Often</option></select><label class="filter-label" for="filter-cannabis">Cannabis</label><select id="filter-cannabis"><option value="all">Any preference</option><option>Never</option><option>Sometimes</option><option>Often</option></select><label class="filter-label" for="filter-workout">Workout</label><select id="filter-workout"><option value="all">Any routine</option><option>Never</option><option>Sometimes</option><option>Often</option><option>Daily</option></select><div class="filter-note"><span>☼</span><p>Filters update your<br />discovery pool.</p></div>'
const visibilityLabel = document.querySelector('.profile-status')
visibilityLabel.outerHTML = '<button class="profile-status" id="profile-visibility" type="button"></button>'
function updateVisibilityControl() { const control = document.querySelector('#profile-visibility'); control.textContent = profileVisible ? '● Live profile' : '○ Hidden from discovery'; control.classList.toggle('hidden', !profileVisible) }
updateVisibilityControl()

const lifestyleFields = '<div class="lifestyle-fields"><div><label for="profile-height">Height</label><input id="profile-height" type="text" placeholder="5 ft 8 in" required disabled /></div><div><label for="profile-ethnicity">Ethnicity</label><input id="profile-ethnicity" type="text" required disabled /></div><div><label for="profile-hair-color">Hair color</label><input id="profile-hair-color" type="text" required disabled /></div><div><label for="profile-drinking">Drinking</label><select id="profile-drinking" disabled><option>Prefer not to say</option><option>Never</option><option>Sometimes</option><option>Often</option></select></div><div><label for="profile-smoking">Smoking</label><select id="profile-smoking" disabled><option>Prefer not to say</option><option>Never</option><option>Sometimes</option><option>Often</option></select></div><div><label for="profile-cannabis">Cannabis</label><select id="profile-cannabis" disabled><option>Prefer not to say</option><option>Never</option><option>Sometimes</option><option>Often</option></select></div><div><label for="profile-workout">Workout</label><select id="profile-workout" disabled><option>Prefer not to say</option><option>Never</option><option>Sometimes</option><option>Often</option><option>Daily</option></select></div></div>'
const identityFields = '<div class="lifestyle-fields"><div><label for="profile-gender">Gender</label><select id="profile-gender" disabled><option>Prefer not to say</option><option>Woman</option><option>Man</option><option>Non-binary</option><option>Genderqueer</option><option>Other</option></select></div><div><label for="profile-sexuality">Sexuality</label><select id="profile-sexuality" disabled><option>Prefer not to say</option><option>Straight</option><option>Gay</option><option>Lesbian</option><option>Bisexual</option><option>Pansexual</option><option>Asexual</option><option>Queer</option><option>Other</option></select></div></div>'
const editLifestyleFields = `${identityFields}${lifestyleFields}`.replaceAll('profile-', 'edit-').replaceAll(' disabled', '')
document.querySelector('#profile-bio').insertAdjacentHTML('beforebegin', identityFields)
document.querySelector('#profile-bio').insertAdjacentHTML('beforebegin', lifestyleFields)
document.querySelector('#edit-bio').parentElement.insertAdjacentHTML('beforebegin', editLifestyleFields)

function normalizeBlockValue(value) { return value.trim().toLowerCase().replace(/\s+/g, ' ') }
function isBlocked(profile) { return blockedPeople.some((blocked) => blocked.value === normalizeBlockValue(profile.name) || blocked.value === normalizeBlockValue(profile.email || '')) }
function isLiked(profile) { return likedProfileIds.has(profile.id) }
async function loadProfiles() { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data, error } = await supabase.from('profiles').select('id,name,age,gender,sexuality,height,ethnicity,hair_color,drinking,smoking,cannabis,workout,major,year,bio,image_url').eq('is_visible', true).neq('id', user.id); if (error || !data?.length) { profiles = []; renderProfile(); renderConnections(); return } profiles = data.map((profile) => ({ ...profile, email: '', prompt: 'A little about me...', answer: profile.bio || 'Still writing this part of my story.', image: profile.image_url || 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=85' })); activeProfile = 0; renderProfile(); renderConnections() }
async function loadMatches() { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: sent } = await supabase.from('likes').select('to_profile').eq('from_profile', user.id); likedProfileIds = new Set((sent || []).map((like) => like.to_profile)); const { data: received } = await supabase.from('likes').select('from_profile').eq('to_profile', user.id); const sentIds = likedProfileIds; const matchIds = (received || []).map((like) => like.from_profile).filter((id) => sentIds.has(id)); const { data: unread } = await supabase.from('messages').select('sender_id').eq('recipient_id', user.id).is('read_at', null); unreadMessageCounts = new Map(); (unread || []).forEach((message) => unreadMessageCounts.set(message.sender_id, (unreadMessageCounts.get(message.sender_id) || 0) + 1)); const { data: matchedProfiles } = matchIds.length ? await supabase.from('profiles').select('id,name,age,major,year,bio,image_url').in('id', matchIds) : { data: [] }; matches = (matchedProfiles || []).map((profile) => ({ ...profile, email: '', prompt: 'A little about me...', answer: profile.bio || 'Still writing this part of my story.', image: profile.image_url || 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=85' })); renderProfile(); renderConnections() }
function renderConnections() { const grid = document.querySelector('.connection-grid'); const count = document.querySelector('#connection-count'); const matchCount = matches.length; count.textContent = `${matchCount} matches`; document.querySelector('#connection-nav-count').textContent = matchCount; grid.innerHTML = matchCount ? matches.map((profile) => `<article class="connection-card">${unreadMessageCounts.has(profile.id) ? '<span class="unread-dot" aria-label="Unread message"></span>' : ''}<img src="${profile.image}" alt="${profile.name}, ${profile.age}" /><div><div class="connection-card-title"><h3>${profile.name}, ${profile.age}</h3></div><p>${profile.major || 'UNC Charlotte student'} · ${profile.year || ''}</p><button class="message-button" data-id="${profile.id}" data-name="${profile.name}">Message <span>→</span></button></div></article>`).join('') : '<div class="empty-connections">No mutual matches yet.</div>'; document.querySelectorAll('.message-button').forEach((button) => button.addEventListener('click', () => openMessages(button.dataset.id, button.dataset.name))); applyBlockedToConnections() }
let activeConversationId = null
let messageChannel = null
let messagePollTimer = null
async function openMessages(profileId, profileName) { if (messagePollTimer) clearInterval(messagePollTimer); activeConversationId = profileId; document.querySelector('#message-title').textContent = `Messages with ${profileName}`; document.querySelector('#message-modal').classList.add('open'); document.querySelector('#message-modal').setAttribute('aria-hidden', 'false'); await markMessagesRead(profileId); await loadMessages(); subscribeToMessages(); messagePollTimer = setInterval(() => { if (activeConversationId) loadMessages() }, 3000); document.querySelector('#message-input').focus() }
async function markMessagesRead(profileId) { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { error } = await supabase.from('messages').update({ read_at: new Date().toISOString() }).eq('sender_id', profileId).eq('recipient_id', user.id).is('read_at', null); if (!error) { unreadMessageCounts.delete(profileId); renderConnections() } }
async function subscribeToMessages() { if (!supabase || !activeConversationId) return; if (messageChannel) await supabase.removeChannel(messageChannel); const conversationId = activeConversationId; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; messageChannel = supabase.channel(`messages:${conversationId}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages' }, (payload) => { const message = payload.new; const belongsToConversation = (message.sender_id === user.id && message.recipient_id === conversationId) || (message.sender_id === conversationId && message.recipient_id === user.id); if (belongsToConversation) loadMessages() }).subscribe() }
async function loadMessages() { const list = document.querySelector('#message-list'); if (!supabase) { list.innerHTML = '<p class="message-empty">Connect Supabase to send messages.</p>'; return } const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from('messages').select('sender_id,body,created_at,read_at').or(`and(sender_id.eq.${user.id},recipient_id.eq.${activeConversationId}),and(sender_id.eq.${activeConversationId},recipient_id.eq.${user.id})`).order('created_at', { ascending: true }); list.innerHTML = data?.length ? data.map((message) => `<div class="message-row ${message.sender_id === user.id ? 'mine' : ''}"><div class="message-bubble ${message.sender_id === user.id ? 'mine' : ''}">${message.body}</div>${message.sender_id === user.id ? `<small class="read-receipt">${message.read_at ? 'Seen' : 'Sent'}</small>` : ''}</div>`).join('') : '<p class="message-empty">Start the conversation.</p>'; list.scrollTop = list.scrollHeight }
function getFilteredProfiles() { const value = (id) => document.querySelector(id).value; const age = value('#filter-age'); const height = value('#filter-height'); return profiles.filter((profile) => { const ageMatch = age === 'all' || (age === '18-21' && profile.age >= 18 && profile.age <= 21) || (age === '22-25' && profile.age >= 22 && profile.age <= 25) || (age === '26+' && profile.age >= 26); const heightInches = Number(profile.height.match(/(\d+) ft (\d+)/)?.[1] || 0) * 12 + Number(profile.height.match(/(\d+) ft (\d+)/)?.[2] || 0); const heightMatch = height === 'all' || (height === 'under-5-6' && heightInches < 66) || (height === '5-6-6' && heightInches >= 66 && heightInches <= 72) || (height === 'over-6' && heightInches > 72); return !isBlocked(profile) && !isLiked(profile) && ageMatch && heightMatch && ['gender', 'sexuality', 'ethnicity', 'hair_color', 'drinking', 'smoking', 'cannabis', 'workout'].every((field) => value(`#filter-${field === 'hair_color' ? 'hair' : field}`) === 'all' || value(`#filter-${field === 'hair_color' ? 'hair' : field}`) === profile[field]) }) }
function renderProfile() { const filteredProfiles = getFilteredProfiles(); if (!filteredProfiles.length) { document.querySelector('#profile-card').innerHTML = '<div class="empty-discovery"><strong>No profiles match these filters.</strong><button id="clear-empty-filters" type="button">Clear filters</button></div>'; document.querySelector('#profile-count').textContent = '0 profiles'; document.querySelector('#clear-empty-filters').addEventListener('click', resetDiscoveryFilters); return } activeProfile %= filteredProfiles.length; const profile = filteredProfiles[activeProfile]; document.querySelector('#profile-card').innerHTML = `<div class="profile-image-wrap"><img src="${profile.image}" alt="${profile.name}, ${profile.age}" /></div><div class="profile-body"><div class="profile-header"><div><h2>${profile.name}, ${profile.age}</h2><p>${profile.major} <span>·</span> ${profile.year}</p></div><button class="save-profile ${savedIds.has(profile.id) ? 'saved' : ''}" aria-label="Save ${profile.name}">${savedIds.has(profile.id) ? '♥' : '♡'}</button></div><div class="prompt"><span>${profile.prompt}</span><strong>${profile.answer}</strong></div></div>`; document.querySelector('#profile-count').textContent = `${activeProfile + 1} of ${filteredProfiles.length} profiles`; document.querySelector('.save-profile').addEventListener('click', () => { savedIds.has(profile.id) ? savedIds.delete(profile.id) : savedIds.add(profile.id); renderProfile(); showToast(savedIds.has(profile.id) ? 'Saved to your shortlist' : 'Removed from your shortlist') }) }
function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('visible'); setTimeout(() => toast.classList.remove('visible'), 2400) }
function normalizeEmail(value) { return value.trim().toLowerCase().replace(/@uncc\.edu$/, '@charlotte.edu') }
async function likeProfile(profile) { if (!supabase) { showToast('Sign in to like profiles'); return } const { data: { user } } = await supabase.auth.getUser(); if (!user) { showToast('Sign in to like profiles'); return } const { error } = await supabase.from('likes').upsert({ from_profile: user.id, to_profile: profile.id }, { onConflict: 'from_profile,to_profile' }); if (error) { showToast(error.message || 'Unable to save like'); return } likedProfileIds.add(profile.id); await loadMatches(); showToast('Like sent. Fingers crossed.') }
function cycleProfile(message) { const count = getFilteredProfiles().length; if (!count) return; const profile = getFilteredProfiles()[activeProfile]; if (message.includes('Like')) likeProfile(profile); activeProfile = (activeProfile + 1) % count; renderProfile(); if (!message.includes('Like')) showToast(message) }
function resetDiscoveryFilters() { document.querySelectorAll('.filters select').forEach((select) => { select.selectedIndex = 0 }); activeProfile = 0; renderProfile(); showToast('Filters reset') }
function renderBlockedList() { const list = document.querySelector('#blocked-list'); list.innerHTML = blockedPeople.length ? blockedPeople.map((blocked, index) => `<div class="blocked-person"><span>${blocked.label}</span><button type="button" data-unblock="${index}">Unblock</button></div>`).join('') : '<p class="blocked-empty">No blocked people.</p>'; list.querySelectorAll('[data-unblock]').forEach((button) => button.addEventListener('click', async () => { const [removed] = blockedPeople.splice(Number(button.dataset.unblock), 1); localStorage.setItem('connects-blocked', JSON.stringify(blockedPeople)); if (supabase) { const { data: { user } } = await supabase.auth.getUser(); if (user) await supabase.from('blocked_users').delete().eq('blocker_id', user.id).or(`blocked_email.eq.${removed.value},blocked_name.eq.${removed.value}`) } renderBlockedList(); renderProfile(); applyBlockedToConnections(); showToast('Person unblocked') })) }
function applyBlockedToConnections() { document.querySelectorAll('.connection-card').forEach((card) => { const name = card.querySelector('h3').textContent.split(',')[0]; card.hidden = blockedPeople.some((blocked) => blocked.value === normalizeBlockValue(name)) }) }
async function loadBlockedPeople() { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from('blocked_users').select('blocked_name, blocked_email'); if (!data) return; const remoteBlocks = data.map((blocked) => { const rawValue = blocked.blocked_email || blocked.blocked_name || ''; return { value: normalizeBlockValue(rawValue), label: rawValue } }); blockedPeople = [...blockedPeople, ...remoteBlocks.filter((remote) => !blockedPeople.some((local) => local.value === remote.value))]; localStorage.setItem('connects-blocked', JSON.stringify(blockedPeople)); renderBlockedList(); renderProfile(); applyBlockedToConnections() }
function setView(view) { document.body.classList.remove('view-discover', 'view-connections', 'view-profile'); document.body.classList.add(`view-${view}`); document.querySelectorAll('.nav-links a').forEach((link) => link.classList.remove('active')); document.querySelector(`#nav-${view}`).classList.add('active'); window.location.hash = view === 'discover' ? 'discover' : view; }
function populateProfileForm() { const profile = JSON.parse(localStorage.getItem('connects-profile') || '{}'); const nameField = document.querySelector('#edit-name'); nameField.value = profile.name || ''; nameField.readOnly = true; if (!document.querySelector('#name-locked-note')) { nameField.insertAdjacentHTML('afterend', '<small class="field-note" id="name-locked-note">Names cannot be changed after profile creation.</small>') } nameField.setAttribute('aria-describedby', 'name-locked-note'); document.querySelector('#edit-age').value = profile.age || ''; document.querySelector('#edit-major').value = profile.major || ''; document.querySelector('#edit-year').value = profile.year || 'Freshman'; document.querySelector('#edit-intent').value = profile.intent || 'Relationship'; document.querySelector('#edit-gender').value = profile.gender || 'Prefer not to say'; document.querySelector('#edit-sexuality').value = profile.sexuality || 'Prefer not to say'; document.querySelector('#edit-height').value = profile.height || ''; document.querySelector('#edit-ethnicity').value = profile.ethnicity || ''; document.querySelector('#edit-hair-color').value = profile.hair_color || ''; document.querySelector('#edit-drinking').value = profile.drinking || 'Prefer not to say'; document.querySelector('#edit-smoking').value = profile.smoking || 'Prefer not to say'; document.querySelector('#edit-cannabis').value = profile.cannabis || 'Prefer not to say'; document.querySelector('#edit-workout').value = profile.workout || 'Prefer not to say'; document.querySelector('#edit-bio').value = profile.bio || ''; document.querySelector('#profile-email').textContent = profile.email || ''; setPhotoPreview('#edit-photo-preview', profile.photo || profile.image_url) }
function setPhotoPreview(selector, photo) { const preview = document.querySelector(selector); preview.src = photo || ''; preview.classList.toggle('visible', Boolean(photo)) }
function readPhoto(input) { return new Promise((resolve, reject) => { const file = input.files[0]; if (!file) { resolve(''); return } const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file) }) }
const swipeCard = document.querySelector('#profile-card')
let swipeStartX = 0
let swipeDeltaX = 0
swipeCard.addEventListener('pointerdown', (event) => { swipeStartX = event.clientX; swipeDeltaX = 0; swipeCard.classList.add('dragging'); swipeCard.setPointerCapture(event.pointerId) })
swipeCard.addEventListener('pointermove', (event) => { if (!swipeCard.classList.contains('dragging')) return; swipeDeltaX = event.clientX - swipeStartX; swipeCard.style.transform = `translateX(${swipeDeltaX}px) rotate(${swipeDeltaX / 16}deg)`; swipeCard.dataset.direction = swipeDeltaX < 0 ? 'pass' : 'like' })
swipeCard.addEventListener('pointerup', () => { if (!swipeCard.classList.contains('dragging')) return; swipeCard.classList.remove('dragging'); swipeCard.style.transform = ''; if (Math.abs(swipeDeltaX) > 90) cycleProfile(swipeDeltaX < 0 ? 'Passed for now' : 'Like sent. Fingers crossed.'); swipeDeltaX = 0; delete swipeCard.dataset.direction })
swipeCard.addEventListener('pointercancel', () => { swipeCard.classList.remove('dragging'); swipeCard.style.transform = ''; swipeDeltaX = 0; delete swipeCard.dataset.direction })
swipeCard.addEventListener('keydown', (event) => { if (event.key === 'ArrowLeft') cycleProfile('Passed for now'); if (event.key === 'ArrowRight') cycleProfile('Like sent. Fingers crossed.') })
renderProfile()
renderConnections()
document.querySelectorAll('.filters select').forEach((select) => select.addEventListener('change', () => { activeProfile = 0; renderProfile() }))
document.querySelector('#reset-discovery-filters').addEventListener('click', resetDiscoveryFilters)
renderBlockedList()
applyBlockedToConnections()
document.querySelector('#block-form').addEventListener('submit', async (event) => { event.preventDefault(); const input = document.querySelector('#block-person').value.trim(); const value = normalizeBlockValue(input); if (!value) return; if (blockedPeople.some((blocked) => blocked.value === value)) { showToast('That person is already blocked'); return } const block = { label: input, value }; blockedPeople.push(block); localStorage.setItem('connects-blocked', JSON.stringify(blockedPeople)); document.querySelector('#block-person').value = ''; renderBlockedList(); renderProfile(); applyBlockedToConnections(); if (supabase) { const { data: { user } } = await supabase.auth.getUser(); if (user) await supabase.from('blocked_users').upsert({ blocker_id: user.id, blocked_name: input.includes('@') ? null : value, blocked_email: input.includes('@') ? value : null }) } showToast('Person blocked') })
loadBlockedPeople()
loadProfiles()
loadMatches()
const modal = document.querySelector('#profile-modal')
const profileFields = document.querySelector('#profile-fields')
const authSubmit = document.querySelector('#auth-submit')
const confirmationNote = document.querySelector('#confirmation-note')
let authMode = 'signup'
function openProfileModal() { modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); document.querySelector('#email').focus() }
function closeModal() { if (!profileCreated) return; modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true') }
document.querySelector('#nav-discover').addEventListener('click', (event) => { event.preventDefault(); setView('discover') })
document.querySelector('#nav-connections').addEventListener('click', (event) => { event.preventDefault(); setView('connections') })
document.querySelector('#nav-profile').addEventListener('click', (event) => { event.preventDefault(); if (profileCreated) { populateProfileForm(); setView('profile') } else openProfileModal() })
document.querySelector('#message-close').addEventListener('click', () => { document.querySelector('#message-modal').classList.remove('open'); document.querySelector('#message-modal').setAttribute('aria-hidden', 'true'); if (messageChannel && supabase) { supabase.removeChannel(messageChannel); messageChannel = null } if (messagePollTimer) { clearInterval(messagePollTimer); messagePollTimer = null } activeConversationId = null })
document.querySelector('#message-modal').addEventListener('click', (event) => { if (event.target.id === 'message-modal') document.querySelector('#message-close').click() })
document.querySelector('#message-form').addEventListener('submit', async (event) => { event.preventDefault(); const input = document.querySelector('#message-input'); const body = input.value.trim(); if (!body || !activeConversationId || !supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) { showToast('Sign in to send messages'); return } const { error } = await supabase.from('messages').insert({ sender_id: user.id, recipient_id: activeConversationId, body }); if (error) { showToast(error.message || 'Unable to send message'); return } input.value = ''; await loadMessages() })
document.querySelector('#profile-visibility').addEventListener('click', async () => { profileVisible = !profileVisible; const profile = JSON.parse(localStorage.getItem('connects-profile') || '{}'); profile.is_visible = profileVisible; localStorage.setItem('connects-profile', JSON.stringify(profile)); updateVisibilityControl(); if (supabase) { const { data: { user } } = await supabase.auth.getUser(); if (user) { const { error } = await supabase.from('profiles').update({ is_visible: profileVisible }).eq('id', user.id); if (error) { profileVisible = !profileVisible; profile.is_visible = profileVisible; localStorage.setItem('connects-profile', JSON.stringify(profile)); updateVisibilityControl(); showToast(error.message || 'Unable to update discovery visibility'); return } } } showToast(profileVisible ? 'Your profile is visible in discovery' : 'Your profile is hidden from discovery') })
async function handleAuthenticatedUser(user) { if (!user) return; const { data: profile } = await supabase.from('profiles').select('*').eq('id', user.id).maybeSingle(); if (profile) { localStorage.setItem('connects-profile', JSON.stringify({ ...profile, email: user.email })); profileCreated = true; document.body.classList.remove('profile-required', 'profile-setup'); closeModal(); setView(window.location.hash === '#connections' ? 'connections' : window.location.hash === '#profile' ? 'profile' : 'discover'); loadProfiles(); loadMatches(); return true } return false }
function enableProfileFields() { document.body.classList.add('profile-setup'); document.querySelector('#profile-title').textContent = 'Create your profile.'; modal.querySelector('p').textContent = 'Your email is confirmed. Add a few details before you start connecting.'; document.querySelector('#email').readOnly = true; document.querySelector('#password').readOnly = true; document.querySelector('#mode-signup').disabled = true; document.querySelector('#mode-signin').disabled = true; authSubmit.hidden = true; confirmationNote.hidden = true; profileFields.setAttribute('aria-disabled', 'false'); profileFields.querySelectorAll('input, select, textarea, button').forEach((field) => { field.disabled = false }) }
async function createProfile() { const email = normalizeEmail(document.querySelector('#email').value); const age = Number(document.querySelector('#profile-age').value); if (age < 18 || age > 99) { showToast('You must be at least 18 to create a profile'); return } const button = document.querySelector('#create-profile'); button.disabled = true; button.innerHTML = 'Creating profile...'; try { const photo = await readPhoto(document.querySelector('#profile-photo')); const profile = { email, name: document.querySelector('#profile-name').value.trim(), age, gender: document.querySelector('#profile-gender').value, sexuality: document.querySelector('#profile-sexuality').value, major: document.querySelector('#profile-major').value.trim(), year: document.querySelector('#profile-year').value, intent: document.querySelector('#profile-intent').value, height: document.querySelector('#profile-height').value.trim(), ethnicity: document.querySelector('#profile-ethnicity').value.trim(), hair_color: document.querySelector('#profile-hair-color').value.trim(), drinking: document.querySelector('#profile-drinking').value, smoking: document.querySelector('#profile-smoking').value, cannabis: document.querySelector('#profile-cannabis').value, workout: document.querySelector('#profile-workout').value, bio: document.querySelector('#profile-bio').value.trim(), photo }; const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Your session expired. Please sign in again.'); const { error } = await supabase.from('profiles').upsert({ id: user.id, name: profile.name, age: profile.age, gender: profile.gender, sexuality: profile.sexuality, major: profile.major, year: profile.year, bio: profile.bio, image_url: profile.photo, height: profile.height, ethnicity: profile.ethnicity, hair_color: profile.hair_color, drinking: profile.drinking, smoking: profile.smoking, cannabis: profile.cannabis, workout: profile.workout }); if (error) throw error; localStorage.setItem('connects-profile', JSON.stringify(profile)); profileCreated = true; document.body.classList.remove('profile-required', 'profile-setup'); closeModal(); showToast('Profile created. Welcome to Connects.'); } catch (error) { showToast(error.message || 'Unable to create profile') } finally { button.disabled = false; button.innerHTML = 'Create my profile <span>→</span>' } }
if (supabase) { supabase.auth.onAuthStateChange(async (event, session) => { if (session?.user?.email_confirmed_at && !profileCreated) { if (!(await handleAuthenticatedUser(session.user))) { document.querySelector('#email').value = session.user.email; enableProfileFields(); showToast('Email confirmed. Finish your profile.') } } }); supabase.auth.getSession().then(async ({ data: { session } }) => { if (session?.user?.email_confirmed_at && !profileCreated && !(await handleAuthenticatedUser(session.user))) { document.querySelector('#email').value = session.user.email; enableProfileFields() } }) }
document.querySelector('#mode-signup').addEventListener('click', () => { authMode = 'signup'; document.querySelector('#mode-signup').classList.add('active'); document.querySelector('#mode-signin').classList.remove('active'); document.querySelector('#password').autocomplete = 'new-password'; authSubmit.textContent = 'Create account →' })
document.querySelector('#mode-signin').addEventListener('click', () => { authMode = 'signin'; document.querySelector('#mode-signin').classList.add('active'); document.querySelector('#mode-signup').classList.remove('active'); document.querySelector('#password').autocomplete = 'current-password'; authSubmit.textContent = 'Sign in →' })
document.querySelector('#profile-photo').addEventListener('change', async (event) => setPhotoPreview('#profile-photo-preview', await readPhoto(event.target)))
document.querySelector('#edit-photo').addEventListener('change', async (event) => setPhotoPreview('#edit-photo-preview', await readPhoto(event.target)))
document.querySelector('#create-profile').addEventListener('click', (event) => { event.preventDefault(); createProfile() })
document.querySelectorAll('.message-button').forEach((button) => button.addEventListener('click', () => showToast(`Message request sent to ${button.dataset.name}`)))
document.querySelector('#profile-edit-form').addEventListener('submit', async (event) => { event.preventDefault(); const editForm = event.currentTarget; const savedProfile = JSON.parse(localStorage.getItem('connects-profile') || '{}'); const photo = await readPhoto(document.querySelector('#edit-photo')); const profile = { ...savedProfile, name: document.querySelector('#edit-name').value.trim(), age: Number(document.querySelector('#edit-age').value), gender: document.querySelector('#edit-gender').value, sexuality: document.querySelector('#edit-sexuality').value, major: document.querySelector('#edit-major').value.trim(), year: document.querySelector('#edit-year').value, intent: document.querySelector('#edit-intent').value, height: document.querySelector('#edit-height').value.trim(), ethnicity: document.querySelector('#edit-ethnicity').value.trim(), hair_color: document.querySelector('#edit-hair-color').value.trim(), drinking: document.querySelector('#edit-drinking').value, smoking: document.querySelector('#edit-smoking').value, cannabis: document.querySelector('#edit-cannabis').value, workout: document.querySelector('#edit-workout').value, bio: document.querySelector('#edit-bio').value.trim(), photo: photo || savedProfile.photo || savedProfile.image_url || '', image_url: photo || savedProfile.photo || savedProfile.image_url || '' }; if (profile.age < 18 || profile.age > 99) { showToast('You must be at least 18'); return } const saveButton = editForm.querySelector('button[type="submit"]'); saveButton.disabled = true; saveButton.innerHTML = 'Saving...'; try { if (supabase) { const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Your session expired. Please sign in again.'); const { error } = await supabase.from('profiles').upsert({ id: user.id, name: profile.name, age: profile.age, gender: profile.gender, sexuality: profile.sexuality, major: profile.major, year: profile.year, bio: profile.bio, image_url: profile.image_url, height: profile.height, ethnicity: profile.ethnicity, hair_color: profile.hair_color, drinking: profile.drinking, smoking: profile.smoking, cannabis: profile.cannabis, workout: profile.workout }); if (error) throw error } localStorage.setItem('connects-profile', JSON.stringify(profile)); saveButton.classList.add('saved'); saveButton.innerHTML = 'Saved'; showToast('Profile saved successfully'); setTimeout(() => { saveButton.classList.remove('saved'); saveButton.innerHTML = 'Save changes <span>→</span>'; saveButton.disabled = false }, 2200); } catch (error) { saveButton.disabled = false; saveButton.innerHTML = 'Save changes <span>→</span>'; showToast(error.message || 'Unable to update profile') } })
document.querySelector('#close-profile').addEventListener('click', closeModal)
modal.addEventListener('click', (event) => { if (event.target === modal && profileCreated) closeModal() })
document.querySelector('#profile-form').addEventListener('submit', async (event) => { event.preventDefault(); const email = normalizeEmail(document.querySelector('#email').value); const password = document.querySelector('#password').value; if (!/@(?:charlotte|uncc)\.edu$/.test(document.querySelector('#email').value.trim().toLowerCase())) { showToast('Use your @charlotte.edu or @uncc.edu email'); return } if (!supabase) { showToast('Connect Supabase to use email and password sign-in'); return } if (password.length < 8) { showToast('Use a password with at least 8 characters'); return } authSubmit.disabled = true; authSubmit.textContent = authMode === 'signup' ? 'Creating account...' : 'Signing in...'; try { if (authMode === 'signin') { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) throw error; const { data: { user } } = await supabase.auth.getUser(); if (await handleAuthenticatedUser(user)) { showToast('Signed in successfully') } else { enableProfileFields(); showToast('Signed in. Finish your profile.') } } else { const { error } = await supabase.auth.signUp({ email, password }); if (error) throw error; authSubmit.disabled = true; authSubmit.textContent = 'Confirmation email sent'; confirmationNote.hidden = false; showToast('Check your inbox for the confirmation link'); } } catch (error) { showToast(error.message || 'Unable to authenticate'); authSubmit.disabled = false; authSubmit.textContent = authMode === 'signup' ? 'Create account →' : 'Sign in →' } })
if (!profileCreated) openProfileModal()
else { const initialView = window.location.hash === '#connections' ? 'connections' : window.location.hash === '#profile' ? 'profile' : 'discover'; if (initialView === 'profile') populateProfileForm(); setView(initialView) }
