import './style.css'
import { supabase } from './supabase.js'

const profiles = [
  { id: 1, name: 'Maya', age: 21, major: 'Architecture', year: 'Junior', prompt: 'A perfect Saturday is...', answer: 'coffee, a little thrift shopping, and finding a new trail.', image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85' },
  { id: 2, name: 'Jordan', age: 22, major: 'Computer Science', year: 'Senior', prompt: 'Currently listening to', answer: 'the same album on repeat while I pretend to study.', image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=85' },
  { id: 3, name: 'Elena', age: 20, major: 'Public Health', year: 'Sophomore', prompt: 'I will never say no to...', answer: 'a picnic at Freedom Park or a spontaneous food truck run.', image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=85' },
]

let activeProfile = 0
let savedIds = new Set()
let profileCreated = Boolean(localStorage.getItem('connects-profile'))

document.querySelector('#app').innerHTML = `
  <header class="topbar"><a class="brand" href="#discover" aria-label="Connects home"><span class="brand-mark">✦</span> connects</a><nav class="nav-links" aria-label="Main navigation"><a class="active" id="nav-discover" href="#discover">Discover</a><a id="nav-connections" href="#connections">Connections <span class="nav-count">3</span></a><a id="nav-profile" href="#profile">Profile</a></nav></header>
  <main>
    <section class="hero-intro discovery-view" id="discover"><div class="eyebrow"><span class="live-dot"></span> Just for Niner Nation</div><h1>Meet someone who<br /><em>gets it.</em></h1><p>Thoughtful connections for students who call Charlotte home.</p><div class="hero-meta"><span>✦ Verified .edu community</span><span class="meta-divider"></span><span>Made for campus life</span></div></section>
    <section class="browse-shell discovery-view" aria-label="Discover profiles">
      <aside class="filters"><div class="filter-heading"><span>How are you connecting?</span></div><label class="filter-label" for="interest">I'm looking for</label><select id="interest"><option>Relationship</option><option>Friend</option></select><div class="filter-note"><span>☼</span><p>We only show verified<br />Charlotte student emails.</p></div></aside>
      <div class="profile-stage"><div class="stage-top"><span id="profile-count">1 of 3 profiles</span></div><article class="profile-card" id="profile-card" tabindex="0" role="button" aria-label="Swipe profile left to pass or right to like"></article><p class="action-hint">Swipe left to pass · swipe right to like</p></div>
    </section>
    <section class="page-view connections-page" id="connections-page" aria-labelledby="connections-title"><div class="page-heading"><div><div class="eyebrow">Your people</div><h2 id="connections-title">Connections</h2><p>Mutual likes, ready for a real conversation.</p></div><span class="page-count">3 matches</span></div><div class="connection-grid">${profiles.map((profile) => `<article class="connection-card"><img src="${profile.image}" alt="${profile.name}, ${profile.age}" /><div><div class="connection-card-title"><h3>${profile.name}, ${profile.age}</h3><span>✓</span></div><p>${profile.major} · ${profile.year}</p><button class="message-button" data-name="${profile.name}">Say hello <span>→</span></button></div></article>`).join('')}</div></section>
    <section class="page-view profile-page" id="profile-page" aria-labelledby="profile-page-title"><div class="page-heading"><div><div class="eyebrow">Your details</div><h2 id="profile-page-title">My profile</h2><p>Keep the details that help the right people find you.</p></div><span class="profile-status">● Live profile</span></div><form class="profile-edit-form" id="profile-edit-form"><div class="profile-edit-grid"><div class="edit-full photo-field"><label for="edit-photo">Profile photo</label><input id="edit-photo" type="file" accept="image/png,image/jpeg,image/webp" /><img id="edit-photo-preview" class="photo-preview" alt="Profile preview" /></div><div><label for="edit-name">First name</label><input id="edit-name" type="text" required /></div><div><label for="edit-age">Age</label><input id="edit-age" type="number" min="18" max="99" required /></div><div><label for="edit-major">Major</label><input id="edit-major" type="text" required /></div><div><label for="edit-year">Class year</label><select id="edit-year"><option>Freshman</option><option>Sophomore</option><option>Junior</option><option>Senior</option><option>Graduate</option></select></div><div><label for="edit-intent">I'm looking for</label><select id="edit-intent"><option>Relationship</option><option>Friend</option></select></div><div class="edit-full"><label for="edit-bio">About you</label><textarea id="edit-bio" rows="5" maxlength="180"></textarea></div></div><div class="profile-edit-footer"><span id="profile-email"></span><button class="primary-button" type="submit">Save changes <span>→</span></button></div></form></section>
  </main>
  <div class="toast" id="toast" role="status"></div>
  <div class="modal-backdrop" id="profile-modal" aria-hidden="true"><div class="auth-modal" role="dialog" aria-modal="true" aria-labelledby="profile-title"><button class="close-modal" id="close-profile" aria-label="Close">×</button><span class="modal-mark">✦</span><h2 id="profile-title">Start with you.</h2><p>Create your profile before you start meeting people in Niner Nation.</p><form id="profile-form"><label for="email">Your student email</label><input id="email" type="email" placeholder="you@charlotte.edu" autocomplete="email" required /><label for="profile-photo">Profile photo</label><input id="profile-photo" type="file" accept="image/png,image/jpeg,image/webp" /><img id="profile-photo-preview" class="photo-preview" alt="Profile preview" /><div class="form-row"><div><label for="profile-name">First name</label><input id="profile-name" type="text" placeholder="Maya" required /></div><div><label for="profile-age">Age</label><input id="profile-age" type="number" min="18" max="99" placeholder="21" required /></div></div><label for="profile-major">Major</label><input id="profile-major" type="text" placeholder="Architecture" required /><label for="profile-year">Class year</label><select id="profile-year"><option>Freshman</option><option>Sophomore</option><option>Junior</option><option>Senior</option><option>Graduate</option></select><label for="profile-intent">I'm looking for</label><select id="profile-intent"><option>Relationship</option><option>Friend</option></select><label for="profile-bio">A little about you <span class="optional">Optional</span></label><textarea id="profile-bio" rows="3" maxlength="180" placeholder="A good coffee spot, a favorite class, or something you want to try..."></textarea><button class="primary-button" type="submit">Create my profile <span>→</span></button><small>Only @charlotte.edu and @uncc.edu emails are accepted.</small></form></div></div>
`

document.body.classList.toggle('profile-required', !profileCreated)

function renderProfile() { const profile = profiles[activeProfile]; document.querySelector('#profile-card').innerHTML = `<div class="profile-image-wrap"><img src="${profile.image}" alt="${profile.name}, ${profile.age}" /><div class="verified-badge">✓</div></div><div class="profile-body"><div class="profile-header"><div><h2>${profile.name}, ${profile.age}</h2><p>${profile.major} <span>·</span> ${profile.year}</p></div><button class="save-profile ${savedIds.has(profile.id) ? 'saved' : ''}" aria-label="Save ${profile.name}">${savedIds.has(profile.id) ? '♥' : '♡'}</button></div><div class="prompt"><span>${profile.prompt}</span><strong>${profile.answer}</strong></div></div>`; document.querySelector('#profile-count').textContent = `${activeProfile + 1} of ${profiles.length} profiles`; document.querySelector('.save-profile').addEventListener('click', () => { savedIds.has(profile.id) ? savedIds.delete(profile.id) : savedIds.add(profile.id); renderProfile(); showToast(savedIds.has(profile.id) ? 'Saved to your shortlist' : 'Removed from your shortlist') }) }
function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('visible'); setTimeout(() => toast.classList.remove('visible'), 2400) }
function cycleProfile(message) { activeProfile = (activeProfile + 1) % profiles.length; renderProfile(); showToast(message) }
function setView(view) { document.body.classList.remove('view-discover', 'view-connections', 'view-profile'); document.body.classList.add(`view-${view}`); document.querySelectorAll('.nav-links a').forEach((link) => link.classList.remove('active')); document.querySelector(`#nav-${view}`).classList.add('active'); window.location.hash = view === 'discover' ? 'discover' : view; }
function populateProfileForm() { const profile = JSON.parse(localStorage.getItem('connects-profile') || '{}'); document.querySelector('#edit-name').value = profile.name || ''; document.querySelector('#edit-age').value = profile.age || ''; document.querySelector('#edit-major').value = profile.major || ''; document.querySelector('#edit-year').value = profile.year || 'Freshman'; document.querySelector('#edit-intent').value = profile.intent || 'Relationship'; document.querySelector('#edit-bio').value = profile.bio || ''; document.querySelector('#profile-email').textContent = profile.email || ''; setPhotoPreview('#edit-photo-preview', profile.photo) }
function setPhotoPreview(selector, photo) { const preview = document.querySelector(selector); preview.src = photo || ''; preview.classList.toggle('visible', Boolean(photo)) }
function readPhoto(input) { return new Promise((resolve, reject) => { const file = input.files[0]; if (!file) { resolve(''); return } const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file) }) }
const swipeCard = document.querySelector('#profile-card')
let swipeStartX = 0
let swipeDeltaX = 0
swipeCard.addEventListener('pointerdown', (event) => { swipeStartX = event.clientX; swipeDeltaX = 0; swipeCard.classList.add('dragging'); swipeCard.setPointerCapture(event.pointerId) })
swipeCard.addEventListener('pointermove', (event) => { if (!swipeCard.classList.contains('dragging')) return; swipeDeltaX = event.clientX - swipeStartX; swipeCard.style.transform = `translateX(${swipeDeltaX}px) rotate(${swipeDeltaX / 16}deg)`; swipeCard.dataset.direction = swipeDeltaX < 0 ? 'pass' : 'like' })
swipeCard.addEventListener('pointerup', () => { if (!swipeCard.classList.contains('dragging')) return; swipeCard.classList.remove('dragging'); swipeCard.style.transform = ''; if (Math.abs(swipeDeltaX) > 90) cycleProfile(swipeDeltaX < 0 ? 'Passed for now' : 'Like sent. Fingers crossed.'); swipeDeltaX = 0; delete swipeCard.dataset.direction })
swipeCard.addEventListener('pointercancel', () => { swipeCard.classList.remove('dragging'); swipeCard.style.transform = ''; swipeDeltaX = 0; delete swipeCard.dataset.direction })
swipeCard.addEventListener('keydown', (event) => { if (event.key === 'ArrowLeft') cycleProfile('Passed for now'); if (event.key === 'ArrowRight') cycleProfile('Like sent. Fingers crossed.') })
renderProfile()
const modal = document.querySelector('#profile-modal')
function openProfileModal() { modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); document.querySelector('#email').focus() }
function closeModal() { if (!profileCreated) return; modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true') }
document.querySelector('#nav-discover').addEventListener('click', (event) => { event.preventDefault(); setView('discover') })
document.querySelector('#nav-connections').addEventListener('click', (event) => { event.preventDefault(); setView('connections') })
document.querySelector('#nav-profile').addEventListener('click', (event) => { event.preventDefault(); if (profileCreated) { populateProfileForm(); setView('profile') } else openProfileModal() })
document.querySelector('#profile-photo').addEventListener('change', async (event) => setPhotoPreview('#profile-photo-preview', await readPhoto(event.target)))
document.querySelector('#edit-photo').addEventListener('change', async (event) => setPhotoPreview('#edit-photo-preview', await readPhoto(event.target)))
document.querySelectorAll('.message-button').forEach((button) => button.addEventListener('click', () => showToast(`Message request sent to ${button.dataset.name}`)))
document.querySelector('#profile-edit-form').addEventListener('submit', async (event) => { event.preventDefault(); const savedProfile = JSON.parse(localStorage.getItem('connects-profile') || '{}'); const photo = await readPhoto(document.querySelector('#edit-photo')); const profile = { ...savedProfile, name: document.querySelector('#edit-name').value.trim(), age: Number(document.querySelector('#edit-age').value), major: document.querySelector('#edit-major').value.trim(), year: document.querySelector('#edit-year').value, intent: document.querySelector('#edit-intent').value, bio: document.querySelector('#edit-bio').value.trim(), photo: photo || savedProfile.photo || '' }; if (profile.age < 18 || profile.age > 99) { showToast('You must be at least 18'); return } localStorage.setItem('connects-profile', JSON.stringify(profile)); if (supabase) { const { data: { user } } = await supabase.auth.getUser(); if (user) await supabase.from('profiles').upsert({ id: user.id, name: profile.name, age: profile.age, major: profile.major, year: profile.year, bio: profile.bio, image_url: profile.photo }) } showToast('Profile updated'); })
document.querySelector('#close-profile').addEventListener('click', closeModal)
modal.addEventListener('click', (event) => { if (event.target === modal && profileCreated) closeModal() })
document.querySelector('#profile-form').addEventListener('submit', async (event) => { event.preventDefault(); const email = document.querySelector('#email').value.trim().toLowerCase(); const age = Number(document.querySelector('#profile-age').value); if (!/@(?:charlotte|uncc)\.edu$/.test(email)) { showToast('Use your @charlotte.edu or @uncc.edu email'); return } if (age < 18 || age > 99) { showToast('You must be at least 18 to create a profile'); return } const button = event.target.querySelector('button'); button.disabled = true; button.innerHTML = 'Creating profile...'; try { const photo = await readPhoto(document.querySelector('#profile-photo')); const profile = { email, name: document.querySelector('#profile-name').value.trim(), age, major: document.querySelector('#profile-major').value.trim(), year: document.querySelector('#profile-year').value, intent: document.querySelector('#profile-intent').value, bio: document.querySelector('#profile-bio').value.trim(), photo }; if (supabase) { const { data: { user } } = await supabase.auth.getUser(); if (user) { const { error } = await supabase.from('profiles').upsert({ id: user.id, name: profile.name, age: profile.age, major: profile.major, year: profile.year, bio: profile.bio, image_url: profile.photo }); if (error) throw error } } localStorage.setItem('connects-profile', JSON.stringify(profile)); profileCreated = true; document.body.classList.remove('profile-required'); closeModal(); showToast('Profile created. Welcome to Connects.'); } catch (error) { showToast(error.message || 'Something went wrong'); } finally { button.disabled = false; button.innerHTML = 'Create my profile <span>→</span>' } })
if (!profileCreated) openProfileModal()
else setView(window.location.hash === '#connections' ? 'connections' : window.location.hash === '#profile' ? 'profile' : 'discover')
